[package]
name = "Advent"
version = "0.1.0"
authors = ["splashofcrimson <splashofcrimson@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "advent_benchmark"
harness = false