[package]
name = "Advent"
version = "0.1.0"
authors = ["splashofcrimson <splashofcrimson@gmail.com>"]
edition = "2018"

[dev-dependencies]
criterion = "0.2"

[lib]
name = "Advent_lib"
path = "src/lib.rs"

[[bench]]
name = "advent_benchmark"
harness = false